# This file describe the pipeline configuration of app. You can override this configuration by creating
# separate file named `pipeline_config.json`. CardChecker merge default configurations with yours so you don't have
# to specify all the configurations. Just specify one's which you want to override. But make sure that
# `pipeline_config.json` file follows the same format of `default_pipeline_config.json`.

company:
  # This is company level configuration. It will be applied to all the boards to whom CardChecker is evaluating.
  defaults:
    # Specify some default values which are constant across your company.
    officeStartHour: "9:00"
    # Office start time. Please specify it in 24-hour clock time.
    officeEndHour: "20:00"
    # Office start time as a String. Please specify it in 24-hour clock time.
    weekendDays:
    # Weekend days. Please specify days in 0(Sunday)-6(Saturday) range.
      - 0
      - 6
    checkerJobDelay: 25
    # Specify the interval after which the trello check job should be run.
  ruleConfig:
    # Here you can config the rules behavior.
    titleWordCount:
      min: 2
      # Minimum number of word count for title of Trello card.
    labelsRequired:
      min: 2
      # Minimum number of labels for Trello card.
    membersRequired:
      min: 1
      # Minimum number of labels for Trello card.
    listOfNewCard:
      listName: tasks
      # Starting list of Trello card.
    pullRequestRequired:
      vcHostingDomain: https://bitbucket.org/
      ignoreLabel: Non Dev
      # Version control hosting service domain.
  cardRules:
    # Specify the default rules which would be applied to every Trello card.
    # It is array of rule names.
    - labelsRequired
    - listOfNewCard
    - titleTitleize
    - titleWordCount
    - descriptionRequired
  listRules:
    # Configure the rules which you want to apply on the transition of card between multiple lists.
    # Here every key, represents the name of list and its value, represents the array of rules which you want
    # to apply on Trello card. Make sure the rules list is array. For eg.
    in progress:
      - dueDateRequired,
      - membersRequired
    in review:
      - checkListItemStateCompletion,
      - pullRequestRequired
    done:
      - dueDateComplete
boards:
  # Company wide configuration is applied to all the boards. But if you want to specify different configuration
  # for boards, here you can specify it. Her every key will be the Trello board id and its value would be Object
  # specifying its configuration. Specify id as a String. The format of configuration is same as company configuration
  # format.
